### PR TITLE
continuous-delivery.md

### PR DESCRIPTION
**Pull request by dgmoreira113**
Hi @G-Thiara and @LSouza16 , what do you think about my explanation about Continuous Delivery? Any comments?

:smiling_imp:

### CODE REVIEW

**Comment by G-Thiara** [comment]
@LSouza16 @dgmoreira113 Sorry guys, forgot to add your handles

**Comment by G-Thiara** [comment]
Good stuff @dgmoreira113. 
Quick suggestion: Can you make the title a bit more descriptive?

**Comment by G-Thiara** [comment]
:+1:

**Comment by dgmoreira113** [comment]
Ok guys, thanks for your comments. It was great working with you. Feedback incorporated into my file!

:+1:

**Comment by LSouza16** [comment]
:+1:

**Pull request merged**
