### PR TITLE
Create Talent Mgmt Insights for managing developers.md

### PR DESCRIPTION
**Pull request by G-Thiara**
Hey Daniel and Lucas.

Can you suggest changes?

### CODE REVIEW

**Comment by G-Thiara** [comment]
@dgmoreira113 @LSouza16 Sorry guys, forgot to add handles in my above comment

**Comment by dgmoreira113** [comment]
Hi @G-Thiara , here are some comments on your file:

Hiring:
1) Ask for reference from other developers and from previous clients so you can learn more about his/her skills, team working skills, etc.
2) Do a 2 hours project, where he should solve a reasonably complex problem in a short period of time.
3) Think about the fit that developer has with your project. For instance, if you're working on an education project, hiring developers who are passionate about education should improve the final results of the project.

Performance management:
1) Make sure the developer uses the right framework to write software. If he/she doesn't know the concepts of Continuous Development or Lean/Kanban, for instance, probably you are going to experience problems whenever testing and shipping your software.
2) I think the team organization should matter to measure performance. Who is going to be responsible for evaluating the developer? The CTO? The VP of Engineering? The team leader? Is the team leader one of the developers?

Overall, great job! Best, Daniel.

**Comment by G-Thiara** [comment]
@LSouza16 @dgmoreira113 Thank you for the detailed feedback. Incorporated those changes. Please have another look.

**Comment by LSouza16** [comment]
:+1:

**Comment by dgmoreira113** [comment]
:+1:

**Pull request merged**
