### PR TITLE
Mvp   ways to validate your idea

### PR DESCRIPTION
**Pull request by LSouza16**
@G-Thiara, @dgmoreira113,

I just created an article on MVP. Could you please give me your feedback on that? 

Thanks guys!

### CODE REVIEW

**Comment by G-Thiara** [comment]
Great job, @LSouza16. Very interesting stuff.

Two comments:
1. Spelling mistake on line 16 "immune" :-)
2. I don't think if 'flyers' should be considered as a MVP. They are a way to test the need but you still have to come with MVP.

**Comment by dgmoreira113** [comment]
Hey @LSouza16 , great job!

Maybe you should also mention that the MVP also allows you to check which features of your software you may want to ship first. If the final version of the project is expected to have a large number of features, the MVP should help you identify which ones to focus in the beginning of the development process. Also, I would make it clearer the role of validating assumptions in this phase of the software development process.

**Comment by LSouza16** [comment]
@G-Thiara and @dgmoreira113 ,

Just incorporated your inputs. Could you check them so I can merge the files?

Thanks,

Lucas Souza

**Comment by G-Thiara** [comment]
:+1:

**Comment by dgmoreira113** [comment]
:+1:

**Comment by LSouza16** [comment]
Thanks guys! 
I'll merge!

**Pull request merged**
